name: Baby Buddy Proxy
version: "1.02a"
panel_icon: "mdi:baby-bottle"
panel_title: Baby Buddy
slug: frigate-proxy
description: Proxy addon for Frigate
url: "https://github.com/huntsman95/babybuddy_proxy"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:5001]/"
watchdog: "http://[HOST]:[PORT:5001]/"
ingress: true
ingress_port: 5001
ingress_entry: /
panel_admin: false
ports:
  5001/tcp: 5001
ports_description:
  5001/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "http://babybuddy.local:5001"
  proxy_pass_host: true
  proxy_pass_real_ip: true
schema:
  server: "match(^https?://.+:\\d+$)"
  proxy_pass_host: bool
  proxy_pass_real_ip: bool
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
